apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ticketing

resources:
  - ../../../base/worker
  - ../shared

patches:
  - path: patches/worker-deployment.yaml
    target:
      kind: Deployment
      name: worker
  - path: patches/worker-serviceaccount.yaml
    target:
      kind: ServiceAccount
      name: worker-service-account

labels:
  - includeSelectors: false
    pairs:
      deployment.region: uksouth
