apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ticketing

resources:
  - ../../../base/scheduler
  - ../shared

patches:
  - path: patches/scheduler-deployment.yaml
    target:
      kind: Deployment
      name: scheduler
  - path: patches/scheduler-serviceaccount.yaml
    target:
      kind: ServiceAccount
      name: scheduler-service-account

labels:
  - includeSelectors: false
    pairs:
      deployment.region: uksouth