apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler-service-account
  namespace: ticketing
  annotations:
    azure.workload.identity/client-id: PLACEHOLDER
  labels:
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/part-of: ticketing-system